chore: update Firefox footnotes for COLRv1 format
Fyrd/caniuse pull request #6158
Opened 2022-01-31 15:58 UTC by yisibl

2022-02-04 00:57 UTC, HM100 requested changes

2022-02-04 00:57 UTC, HM100 commented on features-json/colr-v1.json
> +      "98":"n"
Needs to be removed in order for the checks to be passed. New browser versions can't be added via PRs

2022-02-07 04:07 UTC, merged

2022-02-07 04:07 UTC, Fyrd commented
Thanks! Have added Edge 98.

2022-02-09 13:59 UTC, yisibl commented
Thanks to all.