Update hevc.json
Fyrd/caniuse pull request #6271
Opened 2022-05-15 13:45 UTC by sheik124

Edge has supported HEVC since Version 77.
The UserVoice link previously here was:
1. Dated Oct 21, 2015!!!
2. Has been dead since 2019...
3. https://web.archive.org/web/20190624214549/https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/10311075-hevc-support

2022-05-15 14:37 UTC, Schweinepriester requested changes
Missing `"`, but other than that looking good!

Looks like I'm able to confirm as well, using Edge Version 101.0.1210.47 on Windows 10 21H2 on a Dell XPS 15 9510:

![image](https://user-images.githubusercontent.com/2644614/168478112-1a3fa183-3dcb-4bf1-b418-2871c18bd9e3.png)

https://tests.caniuse.com/hevc shows the video as opposed to Chrome, which only gets the audio.

And I don't even have the [HEVC-extension](https://www.microsoft.com/store/productId/9NMZLZ57R3T7) installed.

There's a possible discussion if this warrants partial support or no support with the note.

2022-05-15 14:37 UTC, Schweinepriester commented on features-json/hevc.json
> +    "4":"Supported only for devices with [hardware support](https://techcommunity.microsoft.com/t5/discussions/updated-dev-channel-build-77-0-211-3-is-live/m-p/745801#M6548)
```suggestion
    "4":"Supported only for devices with [hardware support](https://techcommunity.microsoft.com/t5/discussions/updated-dev-channel-build-77-0-211-3-is-live/m-p/745801#M6548)"
```

2022-05-26 04:31 UTC, Fyrd commented
I think based on the note partial support seems reasonable. Thanks!

2022-05-26 04:31 UTC, Fyrd commented
I think based on the note partial support seems reasonable. Thanks!

2022-05-26 04:31 UTC, merged