Update WebP to show Safari 16 as fully supported
Fyrd/caniuse pull request #6294
Opened 2022-06-08 20:24 UTC by jensimmons

WebP is fully supported on macOS Big Sur and later. Safari 16 can only run on Big Sur and later. So therefore, all installs of Safari 16 have full support of WebP.

2022-06-08 20:26 UTC, Schweinepriester approved these changes

2022-06-08 21:14 UTC, AndyHowarthSbuffles requested changes
`[jensimmons:patch-15]() 
Duplicate of #`

2022-06-08 21:14 UTC, AndyHowarthSbuffles commented
> [jensimmons:patch-15]() Duplicate of #

2022-06-09 04:06 UTC, merged

2022-06-09 04:06 UTC, Fyrd commented
Thanks!