Update iOS 17+ support
Fyrd/caniuse pull request #6883
Opened 2023-10-31 06:56 UTC by rutopio

Reference: COLR support vanished between Safari 16 and 17: [WebKit Bugzilla Bug 262223](https://bugs.webkit.org/show_bug.cgi?id=262223)

2023-10-31 08:10 UTC, Schweinepriester commented
Fixes https://github.com/Fyrd/caniuse/issues/6878.

2023-10-31 08:18 UTC, Schweinepriester requested changes
I have some suggestions - an additional one for which I can't create a code suggestion is to also change (desktop) Safari to `n #4` starting with 17.0 all the way to TP, please.

https://github.com/Fyrd/caniuse/issues/1018#issuecomment-1737111439 appears to show desktop (as well).

2023-10-31 08:18 UTC, Schweinepriester commented on features-json/colr.json
> +      "17.2":"n"
I think it makes sense to put the note on all versions starting 17, assuming it's not intended to be removed.
If it turns out to be intended I guess just `n` it is.
But for now:

```suggestion
      "17.0":"n #4",
      "17.1":"n #4",
      "17.2":"n #4"
```

2023-10-31 08:18 UTC, Schweinepriester commented on features-json/colr.json
> +    "4":"COLR support vanished between Safari 16 and 17: [WebKit Bugzilla Bug 262223](https://bugs.webkit.org/show_bug.cgi?id=262223)"
```suggestion
    "4":"COLRv0 support vanished with Safari 17: [WebKit Bugzilla Bug 262223](https://bugs.webkit.org/show_bug.cgi?id=262223)"
```

2023-10-31 08:27 UTC, rutopio commented
I am certain that iOS 17 does not support on my device. 
Currently, I am running macOS Monterey, and COLRv0 works perfectly on it. 
Need additional feedback from users with the latest macOS versions.

2023-10-31 08:34 UTC, Schweinepriester commented
Even with Safari 17!?
Funky, okay, then we might need a distinction.

Perhaps we can summon @t3chguy: On which version of macOS did you take the second screenshot in https://github.com/Fyrd/caniuse/issues/1018#issuecomment-1737111439? :)

2023-10-31 08:48 UTC, rutopio commented
Sorry for the confusion 😯, I meant that macOS Monterey with Safari 16, and it works perfectly. However, iOS 17 with Safari 17 fail.
That's very possible that both Desktop and Mobile Safari 17 do not support due to the latest Webkit kernel.
Perhaps @t3chguy can provide more details about the desktop side.

2023-10-31 10:11 UTC, t3chguy commented
![image](https://github.com/Fyrd/caniuse/assets/2403652/a6b044aa-1ee1-49e5-9487-b6f730fb0f47)

Here you go

2023-10-31 10:52 UTC, rutopio commented
Thanks!
I've marked both Desktop and Mobile Safari versions above 17 as unsupported.

2023-11-02 04:45 UTC, Fyrd commented
Thanks!

2023-11-02 04:47 UTC, Fyrd commented on features-json/colr.json
>      "3":"On Windows pre 8.1 and macOS Sierra (10.12) and below falls back to using FreeType: [Chromium bug 882844](https://bugs.chromium.org/p/chromium/issues/detail?id=882844#c3)"
```suggestion
    "3":"On Windows pre 8.1 and macOS Sierra (10.12) and below falls back to using FreeType: [Chromium bug 882844](https://bugs.chromium.org/p/chromium/issues/detail?id=882844#c3)",
```

2023-11-02 04:48 UTC, merged